# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "427311f958cc814a311a2545de5d3049"
name = "FuzFuz Customize app"
handle = "fuzfuz-customize-app"
application_url = "https://zones-aids-were-vocals.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://zones-aids-were-vocals.trycloudflare.com/auth/callback",
  "https://zones-aids-were-vocals.trycloudflare.com/auth/shopify/callback",
  "https://zones-aids-were-vocals.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
